from __future__ import annotations

import unittest

from opencompany.prompts import PromptLibrary, default_prompts_dir


class PromptLibraryTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.library = PromptLibrary(default_prompts_dir())

    def test_runtime_message_keys_match_across_locales(self) -> None:
        english = self.library.load_runtime_messages("en")
        chinese = self.library.load_runtime_messages("zh")

        self.assertEqual(set(english), set(chinese))

    def test_root_prompt_clearly_defines_boundaries(self) -> None:
        prompt = self.library.load_agent_prompt("root", "en")

        self.assertIn("Role:", prompt)
        self.assertIn("Context in this conversation:", prompt)
        self.assertIn("including shell", prompt)
        self.assertIn("list_tool_runs", prompt)
        self.assertIn("steer_agent", prompt)
        self.assertIn("send a message or reply to another agent", prompt)
        self.assertIn("new message from the user", prompt)
        self.assertIn("message originating from another agent", prompt)
        self.assertIn("child_agent_id", prompt)
        self.assertIn("multiple tool calls", prompt)
        self.assertIn("Do not call `finish` while unfinished child agents still exist.", prompt)
        self.assertIn("Call `finish` exactly once", prompt)
        self.assertIn("always terminate via a tool call", prompt)
        self.assertIn("define scope boundaries precisely", prompt)
        self.assertIn("what it must not do", prompt)
        self.assertIn("if modification permission is not explicitly granted", prompt)
        self.assertIn("do not modify or delete them", prompt)
        self.assertIn("Never assign overlapping execution scopes", prompt)
        self.assertIn("include the related `child_agent_id`", prompt)
        self.assertIn("do not execute those delegated scopes at root", prompt)
        self.assertIn("If you terminate a child, also terminate other active children that depend", prompt)
        self.assertIn("use `wait_time` or `wait_run`", prompt)
        self.assertIn("Every ended agent should have called `finish`", prompt)
        self.assertIn("inspect the last message", prompt)
        self.assertIn("estimated effort exceeds 24 hours", prompt)

    def test_worker_prompt_clearly_defines_workspace_and_completion_rules(self) -> None:
        prompt = self.library.load_agent_prompt("worker", "en")

        self.assertIn("Role:", prompt)
        self.assertIn("Context in this conversation:", prompt)
        self.assertIn("Work only inside your assigned workspace.", prompt)
        self.assertIn("Prefer decomposition and subagent collaboration;", prompt)
        self.assertIn("list_tool_runs", prompt)
        self.assertIn("steer_agent", prompt)
        self.assertIn("send a message or reply to another agent", prompt)
        self.assertIn("new message from the user or your parent agent", prompt)
        self.assertIn("another non-parent agent", prompt)
        self.assertIn("child_agent_id", prompt)
        self.assertIn("Call `finish` exactly once", prompt)
        self.assertIn("always terminate via a tool call", prompt)
        self.assertIn("Strictly follow instruction-defined task/action scope and constraints.", prompt)
        self.assertIn("define scope boundaries precisely", prompt)
        self.assertIn("what it must not do", prompt)
        self.assertIn("if modification permission is not explicitly granted", prompt)
        self.assertIn("do not modify or delete them", prompt)
        self.assertIn("must not self-initiate extra additions", prompt)
        self.assertIn("references other agents as dependencies", prompt)
        self.assertIn("missing dependency output after dependent agent termination", prompt)
        self.assertIn("Never assign overlapping execution scopes to multiple child agents you create.", prompt)
        self.assertIn("include the responsible `child_agent_id`", prompt)
        self.assertIn("do not execute those delegated scopes yourself in parallel", prompt)
        self.assertIn("also terminate active children that depend on that child's output", prompt)
        self.assertIn("use `wait_time` or `wait_run`", prompt)
        self.assertIn("Every ended agent should have called `finish`", prompt)
        self.assertIn("inspect the last message", prompt)
        self.assertIn("estimated effort exceeds 24 hours", prompt)

    def test_chinese_prompts_mirror_core_constraints(self) -> None:
        root_prompt = self.library.load_agent_prompt("root", "zh")
        worker_prompt = self.library.load_agent_prompt("worker", "zh")

        self.assertIn("角色：", root_prompt)
        self.assertIn("包括 shell", root_prompt)
        self.assertIn("tool_run_id", root_prompt)
        self.assertIn("steer_agent", root_prompt)
        self.assertIn("向其他agent 发送消息或回复时", root_prompt)
        self.assertIn("收到来自用户的新消息", root_prompt)
        self.assertIn("收到来自其他agent 的消息", root_prompt)
        self.assertIn("child_agent_id", root_prompt)
        self.assertIn("不要调用 `finish`", root_prompt)
        self.assertIn("必须通过工具调用收尾", root_prompt)
        self.assertIn("创建subagent 时必须精确划分范围", root_prompt)
        self.assertIn("其能做什么、不能做什么", root_prompt)
        self.assertIn("若未明确说明可修改", root_prompt)
        self.assertIn("不得修改或删除", root_prompt)
        self.assertIn("不要把执行范围重叠的任务分配给多个subagent", root_prompt)
        self.assertIn("提供对应 `child_agent_id`", root_prompt)
        self.assertIn("不要在 root 并行执行已委派的范围", root_prompt)
        self.assertIn("必须同步终止所有依赖其产出的在运行subagent", root_prompt)
        self.assertIn("使用 `wait_time` 或 `wait_run`", root_prompt)
        self.assertIn("每个已结束的agent都应已调用 `finish`", root_prompt)
        self.assertIn("查看最后一条消息", root_prompt)
        self.assertIn("预计耗时超过24小时", root_prompt)
        self.assertIn("角色：", worker_prompt)
        self.assertIn("只能在分配给你的工作区中工作。", worker_prompt)
        self.assertIn("tool_run_id", worker_prompt)
        self.assertIn("steer_agent", worker_prompt)
        self.assertIn("向其他agent 发送消息或回复时", worker_prompt)
        self.assertIn("收到来自用户或父agent 的新消息", worker_prompt)
        self.assertIn("其他非父级agent 的消息", worker_prompt)
        self.assertIn("child_agent_id", worker_prompt)
        self.assertIn("不要调用 `finish`", worker_prompt)
        self.assertIn("必须通过工具调用收尾", worker_prompt)
        self.assertIn("创建subagent 时必须精确划分范围", worker_prompt)
        self.assertIn("其能做什么、不能做什么", worker_prompt)
        self.assertIn("若未明确说明可修改", worker_prompt)
        self.assertIn("不得修改或删除", worker_prompt)
        self.assertIn("不得自作主张额外添加", worker_prompt)
        self.assertIn("必须严格遵循指令中定义的任务与行动范围及约束", worker_prompt)
        self.assertIn("任务依赖指令中提到的其他agent", worker_prompt)
        self.assertIn("依赖尚未完成且对应agent已终止", worker_prompt)
        self.assertIn("不要把执行范围重叠的任务分配给多个你创建的subagent", worker_prompt)
        self.assertIn("提供对应 `child_agent_id`", worker_prompt)
        self.assertIn("不要自己并行执行已委派的范围", worker_prompt)
        self.assertIn("必须同步终止所有依赖其产出的在运行subagent", worker_prompt)
        self.assertIn("优先使用 `wait_time` 或 `wait_run`", worker_prompt)
        self.assertIn("每个已结束的agent都应已调用 `finish`", worker_prompt)
        self.assertIn("查看最后一条消息", worker_prompt)
        self.assertIn("预计耗时超过24小时", worker_prompt)

    def test_runtime_initial_messages_explain_follow_up_context(self) -> None:
        english = self.library.load_runtime_messages("en")
        chinese = self.library.load_runtime_messages("zh")

        self.assertNotIn("max_children_per_agent", english["root_initial"])
        self.assertNotIn("max_active_agents", english["root_initial"])
        self.assertNotIn("max_root_steps", english["root_initial"])
        self.assertNotIn("max_children_per_agent", chinese["root_initial"])
        self.assertNotIn("max_active_agents", chinese["root_initial"])
        self.assertNotIn("max_root_steps", chinese["root_initial"])
        self.assertNotIn("max_root_loops", english["root_initial"])
        self.assertNotIn("max_root_loops", chinese["root_initial"])
        self.assertIn("tool_run_id", english["root_initial"])
        self.assertIn("tool_run_id", english["worker_initial"])
        self.assertIn("child_agent_id", english["root_initial"])
        self.assertIn("child_agent_id", english["worker_initial"])
        self.assertIn("tool_run_id", chinese["root_initial"])
        self.assertIn("tool_run_id", chinese["worker_initial"])
        self.assertIn("child_agent_id", chinese["root_initial"])
        self.assertIn("child_agent_id", chinese["worker_initial"])

    def test_worker_soft_limit_message_still_mentions_unfinished_items_and_errors(self) -> None:
        english = self.library.load_runtime_messages("en")
        chinese = self.library.load_runtime_messages("zh")

        self.assertIn("soft step threshold", english["step_limit_worker"])
        self.assertIn("少量轮次", chinese["step_limit_worker"])
        self.assertIn("unfinished or unclear", english["step_limit_worker"])
        self.assertIn("errors or blockers", english["step_limit_worker"])
        self.assertIn("未完成或不明确", chinese["step_limit_worker"])
        self.assertIn("错误或阻塞", chinese["step_limit_worker"])

    def test_steer_runtime_messages_are_localized(self) -> None:
        english = self.library.load_runtime_messages("en")
        chinese = self.library.load_runtime_messages("zh")

        self.assertEqual(english["steer_message_intro"], "*You received a message:*")
        self.assertEqual(chinese["steer_message_intro"], "*你收到一条消息：*")
